services:
  petra_vision_api:
    build:
      context: .
      dockerfile: docker/AppDevDockerfile
    container_name: petra_vision_api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./rules:/app/rules
      - ./tests:/app/tests
      - ./petra-logo.svg:/app/petra-logo.svg
    env_file:
      - .env
    environment:
      ENABLE_UI: "true"
      LOCAL_WORKDIR: /app/data/tmp
      APP_ENV: development
    restart: unless-stopped
